version: "3.7"
services:

    apromore:
        build: ./apromore
        image: apromore
        depends_on:
            - mysql
            - kafka
        ports:
            - "9100:9000"

    mysql:
        image: mysql:5.6.42
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./mysql_init:/docker-entrypoint-initdb.d"
            - "mysql_data:/var/lib/mysql"
        expose:
            - "3306"

    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        expose:
            - "2181"
    kafka:
        image: wurstmeister/kafka:2.12-2.1.0
        depends_on:
            - zookeeper
        expose:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            
volumes:
  mysql_data:
