version: "3.7"
services:

    apromore:
        build: ./apromore
        image: apromore
        depends_on:
            - mysql
        ports:
            - "9000:9000"

    mysql:
        image: mysql:5.6.42
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./mysql_init:/docker-entrypoint-initdb.d"
            - "mysql_data:/var/lib/mysql"
        expose:
            - "3306"

volumes:
  mysql_data:
